### ISSUE TITLE
Trouble connecting to bitpanda pro

### ISSUE THREAD

**Issue by Watashi26** [nardew/cryptolib-aio#76]
Hello,
there seems to be an error connection to the bitpanda API, because I always receive an error when I'm trying to connect. I created the API key with access to read, trade and withdrawal. However some functions seem to work like `client.get_market_ticker(Pair("BTC", "EUR"))` This returns everything as expected but most of the functions are returning error messages.

The following example dow not work

    from cryptoxlib.CryptoXLib import CryptoXLib
    from cryptoxlib.Pair import Pair
    from cryptoxlib.version_conversions import async_run
    from cryptoxlib.clients.bitpanda.exceptions import BitpandaException
    from cryptoxlib.clients.bitpanda.enums import OrderSide
    
    
    async def main():
        apikey = "key"
        client = CryptoXLib.create_bitpanda_client(apikey)
    
        try:
            await client.create_market_order(Pair("BTC", "EUR"), OrderSide.BUY, "0.00021")
        except BitpandaException as e:
            print(e)
        await client.close()
    
    
    if __name__ == '__main__':
        async_run(main())

**Comment by nardew** [comment]
Good to hear it works!
